### ISSUE TITLE
Release comment from commit message ?

### ISSUE THREAD

**Issue by PowerKiKi** [FluidTYPO3/fluidtypo3-gizzle#3]
I started using this project to auto-release extension to TER. But I could not quite figure out where the release comment comes from. I saw there is a default value in ``ExtensionRepositoryReleasePlugin::DEFAULT_COMMENT``, and I guess that another value could be specified in ``ExtensionRelease.yml``, is that correct ?

If so then I would suggest an alternative. What about, optionally, getting the release comment from the commit message that is being released ? Would that be something you would accept a PR for ?

**Comment by NamelessCoder** [comment]
Sounds like a very reasonable default behavior. Sure, we'll accept a PR for that - but please preserve the support for setting the comment in a settings `.yml` ;)

**Comment by NamelessCoder** [comment]
Just to provide a bit more information:

https://github.com/NamelessCoder/gizzle-typo3-plugins

This package contains the actual plugin that performs the upload and it should be there that this change is made. If you need any details, let me know!

**Comment by PowerKiKi** [comment]
I close this issue, since we now have a better place to track things on https://github.com/NamelessCoder/gizzle-typo3-plugins/issues/2
