### ISSUE TITLE
What to do when repo name does not match extension key?

### ISSUE THREAD

**Issue by fnagel** [FluidTYPO3/fluidtypo3-gizzle#5]
Running into this issue:
````
Directory \u0022my-extension\u0022 has a name indicating it is not a TYPO3 extension. Expected folder name should contain only a-z, 0-9 and underscores. (1412208381)
````

I've seen there is a option in typo3-repository-gizzle to pass the extension key as URL path but this seems not possible when using fluidtypo3-gizzle, right?

Any other way to change extension key per repository?

**Comment by NamelessCoder** [comment]
Totally in a commit/release frenzy here ^^

https://github.com/NamelessCoder/gizzle-typo3-plugins/commit/ac09f2fe74667a23b171178dd277b5e1abe716d0

**Comment by NamelessCoder** [comment]
Implementation sort of similar to https://github.com/NamelessCoder/typo3-repository-gizzle/blob/master/src/GizzlePlugins/ExtensionRepositoryReleasePlugin.php#L47 but builds on an option rather than some third-party user input.

**Comment by fnagel** [comment]
Thanks a lot! Seems to work as expected -- at least the folder is created correctly now. 

TER deploy itself fails at the moment as I'm running into an odd issue, see https://github.com/NamelessCoder/typo3-repository-client/issues/1

I like the idea of setting the extension key in the URL -- that way its not needed to add an specific setting yml for each extension just because the repo name. What about a combination of both options?

**Comment by NamelessCoder** [comment]
Kapow! https://github.com/NamelessCoder/gizzle-typo3-plugins/commit/775947304c479699238cdf14e08c5474c14b6199

**Comment by fnagel** [comment]
Works like expected -- expect that my TER upload fails due to that dependency issues.

Thanks again! Do you have a amazon wishlist? It seems you need some more fine metal music :-D

**Comment by NamelessCoder** [comment]
I wouldn't like receiving SOAP requests with dependency info either, poor TER ^^

I sure do have a wish list, there's a little bit of everything on there: http://www.amazon.co.uk/registry/wishlist/4DBU03X4O79U - thanks! ;)

**Comment by fnagel** [comment]
Did you receive a package? Amazon claims it "will be delivered soon" for more than a month now...

**Comment by NamelessCoder** [comment]
I sure did - thanks for the metal! Received almost a month ago and enjoyed several times since then ;)
